version: 2
jobs:
  build:
    working_directory: ~/guia-de-desenvolvimento-tecnico
    docker:
    - image: circleci/node:7
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install-dependencies
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run:
        name: lint
        command: npm test
    - run:
        name: check-links
        command: npm run check-link-diff
